name: gppvae
channels:
  - soumit
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - h5py
  - matplotlib
  - dask
  - pandas
  - pillow
  - pyyaml
  - pip
  - pip:
    - "wandb<0.13.0"
    - imageio
    - torch==1.0.0
    - torchvision==0.2.1
