name: gppvae
channels:
  - soumit
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - h5py
  - matplotlib
  - dask
  - pandas
  - pytorch=0.4.1
  - torchvision=0.2.1
  - pillow
  - pip
  - pip:
    - "wandb<0.13.0"
    - imageio
